name: Ruby CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: |
        sudo gem install rspec
    - name: Run test
      run: rspec
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: './spec/reports/'
        name: test-ruby
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: test-ruby
          path: spec/reports

